name: pub_server
version: 0.1.6-dev
description: Re-usable components for creating a custom Dart package server.
homepage: https://github.com/dart-lang/pub_server

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http_parser: ^4.0.0
  logging: 1.0.2
  mime: 1.0.1
  pub_semver: ^2.1.0
  shelf: 1.2.0
  yaml: ^3.1.0

dev_dependencies:
  archive: 3.2.1
  args: ^2.3.0
  http: ^0.13.4
  path: ^1.8.1
  pedantic: ^1.11.1
  test: ^1.20.1
